import localFont from "next/font/local";
import "./globals.css";

const voltaireRegular = localFont({
  src: "./fonts/Voltaire-Regular.ttf",
  variable: "--font-voltaire-regular",
  weight: "100 900",
});
const rampartOneRegular = localFont({
  src: "./fonts/RampartOne-Regular.ttf",
  variable: "--font-rampartOne-regular",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${voltaireRegular.variable} ${rampartOneRegular.variable}`}>
        {children}
      </body>
    </html>
  );
}
